"""Version 3 declarative, staged research primitives.

This package is intentionally independent of the legacy generated-Python loop.
Hypotheses are data, interpretation is trusted code, and scoring is a pure pass
over an immutable gross ledger.
"""

from research.v3.campaign import (
    CampaignContract,
    CampaignCoordinator,
    FrozenCandidate,
    FrozenContractMismatch,
    HoldoutConsumedError,
    InvalidTransition,
)
from research.v3.evaluator import Evaluation, Stage, evaluate_ledger
from research.v3.features import (
    CoverageReport,
    CoverageState,
    DarkPoolRecord,
    DerivedFamily,
    FeatureContractError,
    FeatureExport,
    FeatureManifest,
    FeatureSnapshot,
    FlowRecord,
    GexRecord,
    ObservationWindow,
    coverage_report,
    derive_feature_snapshot,
    proprietary_mission_ready,
    required_family_coverage_hash,
)
from research.v3.hypothesis import (
    DiversityDescriptor,
    Hypothesis,
    HypothesisError,
    canonical_hypothesis,
    describe_hypothesis,
    family_is_admissible,
    hypothesis_hash,
    interpret_signal,
    is_near_duplicate,
    make_structure,
    parse_hypothesis,
)
from research.v3.ledger import GrossTradeLedger, GrossTradeRow
from research.v3.opra import (
    DecisionLeg,
    DecisionManifest,
    DecisionRow,
    EntitlementResult,
    EntitlementStatus,
    LegEvidence,
    OpraBlock,
    OpraBlockState,
    OpraBoundaryError,
    ProviderPrice,
    QuoteArtifact,
    collect_opra,
    evaluate_opra_block,
    replay_opra,
    validate_opra_block,
)
from research.v3.proposer import (
    DeclarativeProposal,
    DeclarativeProposer,
    OpenAICompatibleDeclarativeProposer,
    ProposalError,
    parse_proposal_json,
)
from research.v3.runtime import (
    CampaignRuntime,
    ModeledResearchEvaluator,
    StagedResearchData,
    build_modeled_ledgers,
    ensure_stage_stores,
)
from research.v3.stage_store import StageAccess, StageManifest, materialize_stage_stores

__all__ = [
    "CampaignContract",
    "CampaignCoordinator",
    "CampaignRuntime",
    "CoverageReport",
    "CoverageState",
    "DarkPoolRecord",
    "DecisionLeg",
    "DecisionManifest",
    "DecisionRow",
    "DeclarativeProposal",
    "DeclarativeProposer",
    "DerivedFamily",
    "DiversityDescriptor",
    "EntitlementResult",
    "EntitlementStatus",
    "Evaluation",
    "FeatureContractError",
    "FeatureExport",
    "FeatureManifest",
    "FeatureSnapshot",
    "FlowRecord",
    "FrozenCandidate",
    "FrozenContractMismatch",
    "GexRecord",
    "GrossTradeLedger",
    "GrossTradeRow",
    "HoldoutConsumedError",
    "Hypothesis",
    "HypothesisError",
    "InvalidTransition",
    "LegEvidence",
    "ModeledResearchEvaluator",
    "ObservationWindow",
    "OpenAICompatibleDeclarativeProposer",
    "OpraBlock",
    "OpraBlockState",
    "OpraBoundaryError",
    "ProposalError",
    "ProviderPrice",
    "QuoteArtifact",
    "Stage",
    "StageAccess",
    "StageManifest",
    "StagedResearchData",
    "build_modeled_ledgers",
    "canonical_hypothesis",
    "collect_opra",
    "coverage_report",
    "derive_feature_snapshot",
    "describe_hypothesis",
    "ensure_stage_stores",
    "evaluate_ledger",
    "evaluate_opra_block",
    "family_is_admissible",
    "hypothesis_hash",
    "interpret_signal",
    "is_near_duplicate",
    "make_structure",
    "materialize_stage_stores",
    "parse_hypothesis",
    "parse_proposal_json",
    "proprietary_mission_ready",
    "required_family_coverage_hash",
    "replay_opra",
    "validate_opra_block",
]
